---
title: "WWTP"
author: "Emmi Mueller and Jay T. Lennon"
date: "`r format(Sys.time(), '%d %B, %Y')`"
header-includes:
   - \usepackage{array}
output: pdf_document
geometry: margin=2.54cm
---

### Overview
Use data from Wu et al. (2019) to test predictions for effects of residence time on biodiversity

#Set up directory
```{r setup, include = FALSE}
rm(list=ls())
require("knitr")
getwd()
```

# Load packages
```{r}
require("png")
require("vegan")
require("ggplot2")
require("ggpubr")
require("cowplot")
require("ggpmisc")
require("picante")
require("AICcmodavg")
```

#Set up figure themes
```{r figure_setup}
my.cols <- RColorBrewer::brewer.pal(n = 4, name = "Greys")[3:4]

# Set theme for figures in the paper
theme_set(theme_classic() + 
  theme(axis.title = element_text(size = 16),
        axis.title.x = element_text(margin = margin(t = 15, b = 15)),
        axis.title.y = element_text(margin = margin(l = 15, r = 15)),
        axis.text = element_text(size = 14),
        axis.text.x = element_text(margin = margin(t = 5)),
        axis.text.y = element_text(margin = margin(r = 5)),
        axis.line.x = element_blank(),
        axis.line.y = element_blank(),
        axis.ticks.x = element_line(size = 1),
        axis.ticks.y = element_line(size = 1),
        axis.ticks.length = unit(.1, "in"),
        panel.border = element_rect(color = "black", fill = NA, size = 1.5),
        legend.title = element_blank(),
        legend.text = element_text(size = 14),
        strip.text = element_text(size = 14),
        strip.background = element_blank()
        ))
```

# Load data
```{r}
# OTUs (rows) = 96149; sites (columns) = 1188
otu <- read.csv("data/wwtp.otu.csv", sep = ",", header=TRUE)

# Metadata
meta <- read.table("data/wwtp.metadata.txt", sep="\t", header=TRUE)

```

```{r}
#Calculate richness and evenness and add add to metadata
meta$Richness <- NA
for(x in colnames(otu[,-c(1,1188)])){
  meta$Richness[meta$Sample_ID == x] <- specnumber(na.omit(otu[,as.character(x)]))
}

meta$Evenness <- NA
for(x in colnames(otu[,2:1187])){
  meta$Evenness[meta$Sample_ID == x] <- diversity(na.omit(otu[,as.character(x)]), "simpson")
}

#Generate metadata tables for each retention time measurement to remove NAs
meta.pHRT <- subset(meta, meta$HTR_plant != "NA")
meta.aHRT <- subset(meta, meta$HTR_aeration_tank != "NA")
meta.SRT <- subset(meta, meta$SRT != "NA")
```


#Code from Wu et al. 2019 
```{r}
hemi<-ifelse(meta$Latitude>0,"North","South")
meta<-data.frame(cbind(meta,hemi=hemi))
ggplot(meta,aes(x=abs(meta$Latitude),y=(meta$Richness/1000)))+
  geom_point(size=2,alpha=0.6)+
  geom_smooth(method = "lm",formula =y ~ poly(x, 2))+
  xlab("Absolute latitude") +
  ylab(expression(paste("OTU Richness(10"^3, ")"))) +
  stat_poly_eq(formula = y ~ poly(x,2, raw = TRUE), rr.digits = 2, parse = TRUE) +
  theme_bw() +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank())
ggsave("./output/S.lat.pdf")
ggsave("./output/S.lat.png")

```

#Regression of Richness ~ Latitude and Residuals ~ SRT and HRT
```{r}

#Regression of S and E on abs(Latitude)
fit1_r <- lm(meta$Richness ~ abs(meta$Latitude))
fit2_r <- lm(meta$Richness ~ poly(abs(meta$Latitude), 2, raw = TRUE))
fit3_r <- lm(meta$Richness ~ poly(abs(meta$Latitude), 3, raw = TRUE))

fit1_e <- lm(meta$Evenness ~ abs(meta$Latitude))
fit2_e <- lm(meta$Evenness ~ poly(abs(meta$Latitude), 2, raw = TRUE))
fit3_e <- lm(meta$Evenness ~ poly(abs(meta$Latitude), 3, raw = TRUE))

anova(fit1_r, fit2_r, fit3_r)
anova(fit1_e, fit2_e, fit3_e)

S <- ggplot(meta, aes(y = meta$Richness, x = abs(meta$Latitude)))+
  geom_point() +
  geom_smooth(method = "lm", formula = y ~ poly(x, 2, raw = TRUE), col = "red") +
  xlab("abs(latitude)") +
  ylab("S") +
  stat_poly_eq(formula = y ~ poly(x,2, raw = TRUE), rr.digits = 2, parse = TRUE)
ggsave("./output/all.latitude.S.pdf")
ggsave("./output/all.latitude.S.png")

E <- ggplot(meta, aes(y = meta$Evenness, x = abs(meta$Latitude)))+
  geom_point() +
  geom_smooth(method = "lm", formula = y ~ poly(x, 2, raw = TRUE), col = "red") +
  xlab("abs(latitude)") +
  ylab("E") +
  stat_poly_eq(formula = y ~ poly(x,2, raw = TRUE), rr.digits = 2, parse = TRUE)
ggsave("./output/all.latitude.E.pdf")
ggsave("./output/all.latitude.E.png")


#Subset of HRT data - S on abs(Lat) and res_S on aHRT

fit1_hrt_r <- lm(meta.aHRT$Richness ~ abs(meta.aHRT$Latitude))
fit2_hrt_r <- lm(meta.aHRT$Richness ~ poly(abs(meta.aHRT$Latitude), 2, raw = TRUE))
anova(fit1_hrt_r, fit2_hrt_r)

meta.aHRT$Residuals <- fit2_hrt_r$residuals
fit1_hrt_rr <- lm(meta.aHRT$Residuals ~ log(meta.aHRT$HTR_aeration_tank,10))
fit2_hrt_rr <- lm(meta.aHRT$Residuals ~ poly(log(meta.aHRT$HTR_aeration_tank,10), 2, raw = TRUE))
anova(fit1_hrt_rr, fit2_hrt_rr)

hrt_S <- ggplot(meta.aHRT, aes(y = (meta.aHRT$Richness/1000), x = abs(meta.aHRT$Latitude)))+
  geom_point() + 
  geom_smooth(method = "lm", formula = y ~ poly(x, 2, raw=TRUE), col = "red") + 
  xlab("abs(latitude)") + 
  ylab("OTU richness (10^3)")+
  stat_poly_eq(formula = y ~ poly(x, 2, raw = TRUE), rr.digits = 2, parse = TRUE)
ggsave("./output/ahrt.latitude.S.pdf")
ggsave("./output/ahrt.latitude.S.png")

hrt_Sres <- ggplot(meta.aHRT, aes(y = meta.aHRT$Residuals, x = log(meta.aHRT$HTR_aeration_tank, 10))) +
  geom_point() +
  geom_smooth(method = "lm", formula = y~ poly(x,2, raw = TRUE), col = "red") +
  xlab("log(aeration HRT)") +
  ylab("Residuals") +
  stat_poly_eq(formula = y ~ poly(x,2, raw = TRUE), rr.digits = 2, parse = TRUE)
ggsave("./output/ahrt.ahrt.S_residuals.pdf")
ggsave("./output/ahrt.ahrt.S_residuals.png")

ggarrange(hrt_S, hrt_Sres, labels = c("A","B"))
ggsave("./output/ahrt_S_residuals.pdf", width = 10, height = 5)
ggsave("./output/ahrt_S_residuals.png", width = 10, height = 5)
```
#Generate figure of richness and evenness with lowess regression for all three RT types 
```{r}
S_aHRT <- ggplot(meta.aHRT, aes(y = meta.aHRT$Richness, x = log(meta.aHRT$HTR_aeration_tank)))+
  geom_point() + 
  geom_smooth(method = "lm", formula = y ~ poly(x, 2, raw=TRUE), col = "red") + 
  xlab("log(aeration_HRT)") + 
  ylab("S")+
  stat_poly_eq(formula = y ~ poly(x, 2, raw = TRUE), rr.digits = 2, parse = TRUE)
ggsave("./output/ahrt.S.pdf")
ggsave("./output/ahrt.S.png")

S_pHRT <- ggplot(meta.pHRT, aes(y = meta.pHRT$Richness, x = log(meta.pHRT$HTR_plant)))+
  geom_point() + 
  geom_smooth(method = "lm", formula = y ~ poly(x, 2, raw=TRUE), col = "red") + 
  xlab("log(plant_HRT)") + 
  ylab("S")+
  stat_poly_eq(formula = y ~ poly(x, 2, raw = TRUE), rr.digits = 2, parse = TRUE)
ggsave("./output/phrt.S.pdf")
ggsave("./output/phrt.S.png")

S_SRT <- ggplot(meta.SRT, aes(y = meta.SRT$Richness, x = log(meta.SRT$SRT)))+
  geom_point() + 
  geom_smooth(method = "lm", formula = y ~ poly(x, 2, raw=TRUE), col = "red") + 
  xlab("log(SRT)") + 
  ylab("S")+
  stat_poly_eq(formula = y ~ poly(x, 2, raw = TRUE), rr.digits = 2, parse = TRUE)
ggsave("./output/srt.S.pdf")
ggsave("./output/srt.S.png")

```
