---
title: "Biofilm Traits"
author: "Jay T. Lennon"
date: "`r format(Sys.time(), '%d %B, %Y')`"
header-includes:
   - \usepackage{array}
output: pdf_document
geometry: margin=2.54cm
---

### Overview
Use data from Wu et al. (2019) to test predictions for effects of residence time on biodiversity
```{r,setup, include = FALSE}
opts_knit$set(root.dir = '~/GitHub/WWTP')
```

# Set up directories
```{r}
rm(list=ls())
getwd()
```

# Load packages
```{r}
require("png")
require("vegan")
```

# Load data
```{r}
# OTUs (rows) = 96149; sites (columns) = 1188
otu <- read.csv("data/wwtp.otu.csv", sep = ",", header=TRUE)

# Metadata
meta <- read.table("data/wwtp.metadata.txt", sep="\t", header=TRUE)

```

#Calculate richness and evenness and add add to metadata
```{r}
meta$Richness <- NA
for(x in colnames(otu[,-c(1,1188)])){
  meta$Richness[meta$Sample_ID == x] <- specnumber(na.omit(otu[,as.character(x)]))
}

meta$Evenness <- NA
for(x in colnames(otu[,2:1187])){
  meta$Evenness[meta$Sample_ID == x] <- diversity(na.omit(otu[,as.character(x)]), "simpson")
}
```

#Generate figure of richness and evenness with lowess regression for all three RT types 
```{r}
metadata_HTR_plant <- subset(meta, meta$HTR_plant != "NA")
metadata_HTR_aeration <- subset(meta, meta$HTR_aeration_tank != "NA")
metadata_SRT <- subset(meta, meta$SRT != "NA")

png(filename="output/wwtp_div_rt.png", width = 800, height = 800, res = 96*2)

par(mfrow = c(2,3))

plot(log(metadata_HTR_plant$Richness) ~ log(metadata_HTR_plant$HTR_plant), ylab = "log(S)", xlab = expression(paste("log(", tau, ")")), main = "Plant Hydrologic\nRetention Time")
lines(lowess(log(metadata_HTR_plant$Richness) ~ log(metadata_HTR_plant$HTR_plant)), col = "red")
plot(log(metadata_HTR_aeration$Richness) ~ log(metadata_HTR_aeration$HTR_aeration_tank), ylab = "log(S)", xlab = expression(paste("log(", tau, ")")), main = "Aeration Tank\nHydrologic Retention Time")
lines(lowess(log(metadata_HTR_aeration$Richness) ~ log(metadata_HTR_aeration$HTR_aeration_tank)), col = "red")
plot(log(metadata_SRT$Richness) ~ log(metadata_SRT$SRT), ylab = "log(S)", xlab = expression(paste("log(", tau, ")")), main = "Solid Retention Time")
lines(lowess(log(metadata_SRT$Richness) ~ log(metadata_SRT$SRT)), col = "red")

plot(metadata_HTR_plant$Evenness ~ log(metadata_HTR_plant$HTR_plant), ylab = "E", xlab = expression(paste("log(", tau, ")")))
lines(lowess(metadata_HTR_plant$Evenness~log(metadata_HTR_plant$HTR_plant)), col = "red")
plot(metadata_HTR_aeration$Evenness ~ log(metadata_HTR_aeration$HTR_aeration_tank), ylab = "E", xlab = expression(paste("log(", tau, ")")))
lines(lowess(metadata_HTR_aeration$Evenness~log(metadata_HTR_aeration$HTR_aeration_tank)), col = "red")
plot(metadata_SRT$Evenness ~ log(metadata_SRT$SRT), ylab = "E", xlab = expression(paste("log(", tau, ")")))
lines(lowess(metadata_SRT$Evenness ~ log(metadata_SRT$SRT)), col = "red")

dev.off()
graphics.off()

```
